# Generated by Django 3.2.18 on 2023-02-28 16:41
import json

from django.db import migrations, transaction


@transaction.atomic
def add_ingredients(apps, shema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    with open('../../data/ingredients.json', encoding='utf-8') as t:
        ingrs = json.load(t)
    for ing in range(len(ingrs)):
        Ingredient.objects.create(
            name=ingrs[ing]['name'], measurement_unit=ingrs[ing]['measurement_unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_tags'),
    ]

    operations = [migrations.RunPython(add_ingredients),]
