# Generated by Django 4.1.7 on 2023-02-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shoppingcart_favorite_shoppingcart_unique_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
