# Generated by Django 4.1.7 on 2023-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_username_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой почтой уже зарегистрирован'}, max_length=100, unique=True, verbose_name='email'),
        ),
    ]
