# Generated by Django 4.1.7 on 2023-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'Пользователь с такой почтой уже зарегистрирован'}, max_length=254, unique=True, verbose_name='email'),
        ),
    ]
